#!/bin/bash

## Versions
BOOTSTRAP_VERSION="2.2.1"

# Make sure we are in the root directory where the setup executable lives
if [ "`echo $0 | cut -c1`" = "/" ]; then
  cd `dirname $0`
else
  cd `pwd`/`echo $0 | sed -e s/setup//`
fi
pwd

## Check for required executables
for ex in virtualenv bower pip python2.7
do
    command -v $ex >/dev/null 2>&1 || { echo >&2 "Executable '$ex' is required but not installed.  Aborting."; exit 1; }
done

# Check for normal files we expect
for f in manage.py requirements.txt django_base/settings.py
do
  if [ ! -e $f ];
  then
    echo "File $f not found.  Aborting"
      exit 1;
  fi
done

STATIC_ROOT="./django_base/static"

virtualenv --python=`which python2.7` ./.env --no-site-packages
source .env/bin/activate

mkdir -p "$STATIC_ROOT/js"
mkdir -p "$STATIC_ROOT/less"
mkdir -p "$STATIC_ROOT/img"

bower install "bootstrap#$BOOTSTRAP_VERSION"
cp components/bootstrap/js/*.js "$STATIC_ROOT/js/"
cp components/bootstrap/less/*.less "$STATIC_ROOT/less/"
cp components/bootstrap/img/*.png "$STATIC_ROOT/img/"

rm -rf components

pip install -r requirements.txt -f https://s3.amazonaws.com/sheepdog-assets/feta/index.html --no-index
