#!/bin/bash
## Downloads the static files

## Versions
BOOTSTRAP_VERSION="2.2.1"

## First, we grab the static files location.  
## We ASSUME this is in the folder that settings exists in.
if  ! [  -a manage.py ] 
    then
        echo "Your location is bad and you should feel bad."
        exit
fi

ROOT=`find . -name settings.py | perl -ne'/\/([A-Za-z0-9_]*)\/settings.py/ && print $1'`

if [ -z $ROOT ] 
    then
        echo "Settings not found! Exiting."
        exit
fi

STATIC_ROOT="./$ROOT/static"

mkdir -p "$STATIC_ROOT/js"
mkdir -p "$STATIC_ROOT/less"
mkdir -p "$STATIC_ROOT/img"

bower install "bootstrap#$BOOTSTRAP_VERSION"
cp components/bootstrap/js/*.js "$STATIC_ROOT/js/"
cp components/bootstrap/less/*.less "$STATIC_ROOT/less/"
cp components/bootstrap/img/*.png "$STATIC_ROOT/img/"

rm -rf components

pip install -r requirements.txt