#!/bin/bash

PROJECT=django_base

function echo_exit {
    echo ABORTING: $*
    exit 1
}

# Make sure we are in the root directory where the setup executable lives
if [ "`echo $0 | cut -c1`" = "/" ]; then
  cd `dirname $0`
else
  cd `pwd`/`echo $0 | sed -e s/setup//`
fi

# Check that django_base is in each of these files, and replace it with $PROJECT
if [ ! -e $PROJECT ]
then
  _FILES=`echo {package,bower}.json manage.py django_base/{settings,wsgi}.py`
  for f in $_FILES
  do
    if ! grep -q django_base $f
    then echo_exit "File $f does not have the string django_base... something is awry"
    fi
  done
  sed -i.tmp "s/django_base/$PROJECT/g" {package,bower}.json manage.py django_base/{settings,urls,wsgi}.py && rm -f *.tmp */*.tmp
  git mv django_base $PROJECT
fi

## Check for PROJECT name in json files
for f in package.json bower.json
do
  if ! grep -q "name.*:.*$PROJECT" $f
  then echo_exit "File $f should have name set to the project name $PROJECT"
  fi
done

## Check for required executables
for ex in virtualenv npm pip python2.7 virtualenvwrapper.sh bower
do
    command -v $ex >/dev/null 2>&1 || { echo >&2 echo_exit "Executable '$ex' is required but not installed.  Aborting."; }
done

# Check for normal files we expect
for f in manage.py requirements.txt $PROJECT/settings.py
do
  if [ ! -e $f ]
  then echo_exit "File $f not found"
  fi
done

# Check if we already ran the setup script:
for f in $PROJECT/static/bower $WORKON_HOME/$PROJECT
do
  if [ -e $f ]
  then
    echo "File $f already exists; perhaps you already ran the setup?"
    echo "To try again, run the following first: "
    echo "   rm -rf $PROJECT/static/bower ; rmvirtualenv $PROJECT"
    exit 1;
  fi
done

# Replace secret key on project
sed -i.tmp "s%SECRET_KEY = ['][^']*[']%SECRET_KEY = '`openssl rand -base64 48`'%g" django_base/settings.py && rm -f *.tmp */*.tmp

# Install all dependencies
source `which virtualenvwrapper.sh`
mkvirtualenv --python=python2.7  --no-site-packages $PROJECT
pip install -r requirements.txt -f https://s3.amazonaws.com/sheepdog-assets/feta/index.html --no-index
npm install

printf 'export PATH=%s/node_modules/.bin:$PATH\n' `pwd` >> $VIRTUAL_ENV/bin/postactivate

# Warning:  If node is too new a version, you'll get an error; not sure why
#    TypeError('Arguments to path.join must be strings');
# See, for example:  https://github.com/1602/compound/issues/462
# OK with v0.8.21

bower install

echo "============================"
echo "TO PROCEED:"
echo "(1) => Create database $PROJECT"
echo "(2) workon $PROJECT"
echo "(3) ./manage.py syncdb"
echo "(4) ./manage.py migrate"
